name: Publish Docker image# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the 7.4.x-dev branch
  push:
    branches: [ 7.4.x-dev ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mck7/php-fpm
          tag_with_ref: true
