# This is a basic workflow to help you get started with Actions

name: Docker Build and Push

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the 7.4.x-dev branch
  push:
    branches: [ 7.4.x-dev ]
  pull_request:
    branches: [ 7.4.x-dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login to Docker Hub
        run: docker login --username="${DOCKER_USER}" --password="${DOCKER_PASS}"

      # Runs a set of commands using the runners shell
      - name: Build the Docker image
        run: docker build --rm -t mck7/apache-php:7.4.x-dev .

      # Runs a set of commands using the runners shell
      - name: Push the Docker image
        run: docker push mck7/apache-php:7.4.x-dev"
